# Generated by Django 3.2 on 2021-04-18 14:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedurls',
            options={'verbose_name': 'Stored URL', 'verbose_name_plural': 'Stored URLs'},
        ),
        migrations.AlterField(
            model_name='storedurls',
            name='expiry_time',
            field=models.DateTimeField(default=core.models.default_expiry_time),
        ),
    ]
