# Generated by Django 3.2 on 2021-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210418_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedurls',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
